# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: AddressParser - Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Swift 6.0.0
      uses: fwal/setup-swift@v1
      with:
        swift-version: '6.0.0'
    
    - name: Build AddressParser library
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
